// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsRX1O90BOOzJ5sBE2mguy7gJjqGFgRFo',
    appId: '1:569543818746:web:fbd8c93b2e1068a8803843',
    messagingSenderId: '569543818746',
    projectId: 'aashi-e8b74',
    authDomain: 'aashi-e8b74.firebaseapp.com',
    storageBucket: 'aashi-e8b74.firebasestorage.app',
    measurementId: 'G-CJDWWDLENQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcDRW1oSVBjJDaSLwChWuJM61EuZD96pY',
    appId: '1:569543818746:android:593e33fd40fcd589803843',
    messagingSenderId: '569543818746',
    projectId: 'aashi-e8b74',
    storageBucket: 'aashi-e8b74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa_DMicDzUH0xLZv-367QiMimXZT1nujg',
    appId: '1:569543818746:ios:dd3e130f19623afe803843',
    messagingSenderId: '569543818746',
    projectId: 'aashi-e8b74',
    storageBucket: 'aashi-e8b74.firebasestorage.app',
    iosClientId:
        '569543818746-og3f2ro44veketht9bcte95e6igcbrkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa_DMicDzUH0xLZv-367QiMimXZT1nujg',
    appId: '1:569543818746:ios:dd3e130f19623afe803843',
    messagingSenderId: '569543818746',
    projectId: 'aashi-e8b74',
    storageBucket: 'aashi-e8b74.firebasestorage.app',
    iosClientId:
        '569543818746-og3f2ro44veketht9bcte95e6igcbrkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsRX1O90BOOzJ5sBE2mguy7gJjqGFgRFo',
    appId: '1:569543818746:web:16c0cb81c0e92cba803843',
    messagingSenderId: '569543818746',
    projectId: 'aashi-e8b74',
    authDomain: 'aashi-e8b74.firebaseapp.com',
    storageBucket: 'aashi-e8b74.firebasestorage.app',
    measurementId: 'G-GK3B49STT4',
  );
}
